name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: GitHub Docker Action
      uses: matootie/github-docker@v1.0.1
      with:
        # GitHub user to publish the image on behalf of.
        username: khromov
        # GitHub Personal Access Token for the user.
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        # The repository to push the image to. Defaults to current repository. Must be specified in format user/repo
        #repositoryName: khromov/docker-node-hello-world # optional
        # The desired name for the image. Defaults to current repository name.
        #imageName: docker-node-hello-world # optional
        # The desired tag for the image. Defaults to current branch or release version number.
        # imageTag: # optional
